apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sunny-prod
resources:
  - namespace.yaml
  - resource-quota.yaml
  # Manoj adds per-service: deployment-*.yaml, service-*.yaml, servicemonitor-*.yaml, configmap-*.yaml
